# Generated by Django 3.1.5 on 2021-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210122_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol',
            field=models.CharField(max_length=4),
        ),
    ]
