# Generated by Django 3.1.5 on 2021-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol',
            field=models.CharField(max_length=6),
        ),
    ]
